[project]
authors = ["Ryan Oates <ryanfullstack@icloud.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "Add a short description here"
name = "mcp-projects"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.1.0.dev2025021016,<26"
jq = ">=1.7.1,<2"
pip = ">=25.0.1,<26"
anthropic = ">=0.45.2,<0.46"
openai = ">=1.61.0,<2"
uv = ">=0.5.29,<0.6"
